# -*- coding: utf-8 -*-
"""water stored in bars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1leJmhSf79eFUQ278Bwl5SZmy1CpzFLnU

Problem 3) how much water stored in between bars
"""

def stored_water(height,nuofbars):
  store_water=0
  for i in range(1, nuofbars - 1):
    left = height[i]
    for j in range(i):
            left = max(left,height[j])
    right = height[i]
    for j in range(i + 1, nuofbars):
            right = max(right, height[j])
    store_water = store_water + (min(left, right) - height[i])
  return store_water

height=[1,2,0,3,1,0,1]
nuofbars=len(height)
print("water stored in the bars =",stored_water(height,nuofbars))

import matplotlib.pyplot as plt
x=[1,2,3,4,5,6,7]
plt.bar(x,height)